## Housing Analysis Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_parquet('/Users/elliotdable/Documents/phd/justin_project/foundations_london_housing_2015_2025_20261005T192558Z.parquet')

In [2]:
df.head()

,name,area_name,reference,uid,url,description,app_type,app_size,status,decision,...,n_comments,n_documents,n_statutory_days,n_dwellings,housing_relevance_score,lat,lng,ward_name,agent_company,case_officer
0,Barking/15/01590/CLU_P,Barking and Dagenham,None,15/01590/CLU_P,https://online-befirst.lbbd.gov.uk/planning/in...,Application for a certificate of lawfulness fo...,Outline,Small,Permitted,Lawful (Certificate),...,NaN,4.0,56.0,NaN,0.988648,51.541061,0.085255,Abbey,,See source
1,Barking/15/01592/CLU_P,Barking and Dagenham,None,15/01592/CLU_P,https://online-befirst.lbbd.gov.uk/planning/in...,Application for a certificate of lawfulness fo...,Outline,Small,Permitted,Lawful (Certificate),...,NaN,4.0,56.0,NaN,0.981609,51.563198,0.121574,Becontree,,See source
2,Barking/15/01593/FUL,Barking and Dagenham,None,15/01593/FUL,https://online-befirst.lbbd.gov.uk/planning/in...,Change of use of library as Royal British Legi...,Full,Small,Permitted,Approved,...,NaN,7.0,56.0,NaN,0.943073,51.539070,0.154182,Village,,See source
3,Barking/15/01594/FUL,Barking and Dagenham,None,15/01594/FUL,https://online-befirst.lbbd.gov.uk/planning/in...,Erection of part single/part two storey rear e...,Full,Small,Permitted,Approved,...,NaN,4.0,56.0,NaN,0.997902,51.554550,0.114968,Becontree,,See source
4,Barking/15/01596/PRIOR6,Barking and Dagenham,None,15/01596/PRIOR6,https://online-befirst.lbbd.gov.uk/planning/in...,Application for prior approval of proposed sin...,Outline,Small,Permitted,Prior Approval Not Required,...,NaN,5.0,42.0,NaN,0.964838,51.535976,0.086667,Gascoigne,,See source

In [3]:
df.columns

Index(['name', 'area_name', 'reference', 'uid', 'url', 'description',
       'app_type', 'app_size', 'status', 'decision', 'decided_by',
       'start_date', 'decided_date', 'target_decision_date',
       'days_to_decision', 'last_changed', 'fetched_at', 'n_comments',
       'n_documents', 'n_statutory_days', 'n_dwellings',
       'housing_relevance_score', 'lat', 'lng', 'ward_name', 'agent_company',
       'case_officer'],
      dtype='object')

In [4]:
df['start_date'] = pd.to_datetime(df['start_date'])
df['target_decision_date'] = pd.to_datetime(df['target_decision_date'])
df['decided_date'] = pd.to_datetime(df['decided_date'])

In [5]:
df = df[df['start_date'].dt.year > 2020]

In [6]:
df['housing_relevance_score'].min(), df['housing_relevance_score'].max(), df['housing_relevance_score'].mean(), df['housing_relevance_score'].median()

(0.9000021808108956, 0.9999967287908168, 0.9676774011030934, 0.976028166833186)

In [ ]:
for year in df['start_date'].dt.year.unique():
    plt.hist(df[df['start_date'].dt.year == year]['housing_relevance_score'], bins=50, edgecolor='black')
    plt.axvline(df[df['start_date'].dt.year == year]['housing_relevance_score'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')
    plt.legend()
    plt.title(f'Distribution of Housing Relevance Scores in {year}')
    plt.xlabel('Housing Relevance Score')
    plt.ylabel('Frequency')
    plt.show()

In [ ]:
for year in df['decided_date'].dt.year.unique():
    plt.hist(df[df['decided_date'].dt.year == year]['housing_relevance_score'], bins=50, edgecolor='black')
    plt.axvline(df[df['decided_date'].dt.year == year]['housing_relevance_score'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')
    plt.legend()
    plt.title(f'Distribution of Housing Relevance Scores in {year}')
    plt.xlabel('Housing Relevance Score')
    plt.ylabel('Frequency')
    plt.show()

In [ ]:
df[['app_type', 'app_size']]

In [10]:
df.app_type.value_counts(), df.app_type.value_counts().keys()

(app_type
 Full           131702
 Outline         66626
 Conditions      27079
 Amendment       14744
                  1971
 Heritage         1044
 Other             230
 Trees             165
 Advertising       110
 Telecoms          109
 Name: count, dtype: int64,
 Index(['Full', 'Outline', 'Conditions', 'Amendment', '', 'Heritage', 'Other',
        'Trees', 'Advertising', 'Telecoms'],
       dtype='object', name='app_type'))

In [ ]:
for app_type in df['app_type'].unique():
    plt.hist(df[df['app_type'] == app_type]['housing_relevance_score'], bins=50, edgecolor='black')
    plt.axvline(df[df['app_type'] == app_type]['housing_relevance_score'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')
    plt.legend()
    plt.title(f'Distribution of Housing Relevance Scores for {app_type}')
    plt.xlabel('Housing Relevance Score')
    plt.ylabel('Frequency')
    plt.show()

In [12]:
df_demolition = df[df['description'].str.lower().str.contains('demolition')]

In [13]:
(100*df_demolition.shape[0]/df.shape[0])

24.285421281483305

In [ ]:
n = 0
for val in df['description'].value_counts().keys():
    print(val)
    n+=1

print(n)

In [15]:
df[(~df.description.str.lower().str.contains('extension')) 
   & ~df.description.str.lower().str.contains('demolition')
   & ~df.description.str.lower().str.contains('erection')
   & ~df.description.str.lower().str.contains('change of use')
   & ~df.description.str.lower().str.contains('variation')
   & ~df.description.str.lower().str.contains('alteration')
   & ~df.description.str.lower().str.contains('application')
   & ~df.description.str.lower().str.contains('installation')
   & ~df.description.str.lower().str.contains('removal')
   & ~df.description.str.lower().str.contains('amendment')
   & ~df.description.str.lower().str.contains('construction')
   & ~df.description.str.lower().str.contains('redevelopment')
   & ~df.description.str.lower().str.contains('replacement')
   ]['description']

1610      Rear loft conversion including dormer roof and...
2119      Change use of ground floor rear area from Clas...
5074      One front dormer and two rear dormers, with tw...
5512             Enlargement of existing rear dormer window
5757      Insertion of rear dormer window and new side g...
                                ...
243267    Use of a single family dwelling as three resid...
243290    New dormer window at rear elevation and two ne...
243449    Introduction of 3 conservation roof lights to ...
243468    Details of the final layout of the retail acco...
243577    Detailed drawings of the dormers and dormer wi...
Name: description, Length: 9290, dtype: object

In [16]:
extensions_df = df[df.description.str.lower().str.contains('extension')]
demolition_df = df[df.description.str.lower().str.contains('demolition')]
erection_df = df[df.description.str.lower().str.contains('erection')]
change_of_use_df = df[df.description.str.lower().str.contains('change of use')]
variation_df = df[df.description.str.lower().str.contains('variation')]
alteration_df = df[df.description.str.lower().str.contains('alteration')]
application_df = df[df.description.str.lower().str.contains('application')]
installation_df = df[df.description.str.lower().str.contains('installation')]
removal_df = df[df.description.str.lower().str.contains('removal')]
amendment_df = df[df.description.str.lower().str.contains('amendment')]
construction_df = df[df.description.str.lower().str.contains('construction')]
redevelopment_df = df[df.description.str.lower().str.contains('redevelopment')]
replacement_df = df[df.description.str.lower().str.contains('replacement')]
remnants_df = df[~df.description.str.lower().str.contains('extensions')]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

terms = ['extension', 'demolition', 'erection', 'change of use', 'variation',
         'alteration', 'application', 'installation', 'removal', 'amendment',
         'construction', 'redevelopment', 'replacement']

desc = df['description'].str.lower()
flags = pd.DataFrame({t: desc.str.contains(t, regex=False, na=False) for t in terms}).astype(int)
co = flags.T @ flags

# Drop the first row and last column; they would only hold the diagonal or blanks
co_plot = co.iloc[1:, :-1]
rows, cols = co_plot.index, co_plot.columns

# Hide everything above the old diagonal
mask = np.triu(np.ones(co_plot.shape, dtype=bool), k=1)
data = np.ma.masked_array(co_plot.values, mask)

fig, ax = plt.subplots(figsize=(10, 8))
im = ax.imshow(data, cmap='Blues')

ax.set_xticks(range(len(cols)), cols, rotation=45, ha='right')
ax.set_yticks(range(len(rows)), rows)
ax.spines[:].set_visible(False)

vmax = data.max()
for i in range(len(rows)):
    for j in range(i + 1):
        v = co_plot.iat[i, j]
        ax.text(j, i, f'{v:,}', ha='center', va='center', fontsize=8,
                color='white' if v > vmax * 0.6 else '#333333')

fig.colorbar(im, ax=ax, shrink=0.8, label='Descriptions containing both terms')
ax.set_title('Co-occurrence of terms in descriptions')
plt.tight_layout()
plt.show()

In [ ]:
import re
import numpy as np
import matplotlib.pyplot as plt

categories = {
    'New build':           ['erection', 'construction', 'redevelopment'],
    'Extension': ['extension'],
    'Demolition/removal':  ['demolition', 'removal'],
    'Replacement/install': ['replacement', 'installation'],
    'Change':  ['change of use',  'alteration'],
    'Amendment/variation': ['variation', 'amendment', 'application'],
}

desc = df['description'].str.lower()

# A row belongs to a category if it contains any of that category's terms
cat_flags = pd.DataFrame({
    cat: desc.str.contains('|'.join(map(re.escape, words)), na=False)
    for cat, words in categories.items()
}).astype(int)

co = cat_flags.T @ cat_flags


def plot_cooccurrence(co, title):
    # Drop the diagonal, plus the first row and last column it leaves empty
    co_plot = co.iloc[1:, :-1]
    rows, cols = co_plot.index, co_plot.columns

    mask = np.triu(np.ones(co_plot.shape, dtype=bool), k=1)
    data = np.ma.masked_array(co_plot.values, mask)

    fig, ax = plt.subplots(figsize=(8, 6.5))
    im = ax.imshow(data, cmap='Blues')

    ax.set_xticks(range(len(cols)), cols, rotation=45, ha='right')
    ax.set_yticks(range(len(rows)), rows)
    ax.spines[:].set_visible(False)

    vmax = data.max()
    for i in range(len(rows)):
        for j in range(i + 1):
            v = co_plot.iat[i, j]
            ax.text(j, i, f'{v:,}', ha='center', va='center', fontsize=9,
                    color='white' if v > vmax * 0.6 else '#333333')

    fig.colorbar(im, ax=ax, shrink=0.8, label='Descriptions containing both')
    ax.set_title(title)
    plt.tight_layout()
    plt.show()


plot_cooccurrence(co, 'Co-occurrence of categories in descriptions')

In [19]:
demolition_df['description'].values

array(['Demolition of existing garage and construction of a single storey rear/side extension and demolition of chimney.',
       'Conversion of existing 2 bedroom dwelling house into 2No. Flats (1x two bedroom and 1x one bedroom) including demolition of garage and construction of two storey side and single storey rear extension.',
       'Demolition of existing garage and construction of a single storey side extension to provide a study and bathroom for disabled occupant.',
       ...,
       'Demolition of all existing buildings (Class B2) and structures and associated works and erection of new buildings comprising a mixed-use redevelopment of residential (Class C3) and commercial (Class E) uses, together with all landscaping, public realm, cycle parking, car parking, highways works and associated works (see associated application ref. 2025/4364/P at 3-30 Cedar Way). (Re-consultation due to publication of Environmental Statement addendum).',
       'Demolition of all existing buildings (Class E and B8) and structures and associated works and erection of new buildings comprising a mixed use redevelopment of residential (Class C3) and commercial (Class E) uses, together with all landscaping, public realm, cycle parking, car parking, highways works and associated works. (See associated application ref. 2025/4341/P at 120-136 Camley Street). (Re-consultation due to publication of Environmental Statement addendum).',
       'Amendments to planning permission dated 1 April 2021 (RN: 21/01564/NMA) for which itself Varied application (RN: 19/03844/FULL) for which itself varied of condition 1 of planning permission dated 21 December 2017 (RN: 17/00938/FULL) which itself varied Condition 2 of planning permission dated 2 November 2003 (RN: 02/06302/FULL) for the: Demolition of existing buildings and erection of residential building of 6-8 storeys comprising 66 apartments including 17 affordable units and provision of 64 parking spaces in two basements. NAMELY, to allow the removal of 17 affordable housing units from the Description of Development, changes to internal layout and approved drawings and documents as listed in Condition 25.'],
      dtype=object)

The description column is very ambiguous as there are spelling mistakes, synonyms and just general ambiguity. We therefore need to classify/catgeorise this column more effectively, potentially with the use of an external pre-trained LLM/sentiment-analysis tool.

In [20]:
df.columns

Index(['name', 'area_name', 'reference', 'uid', 'url', 'description',
       'app_type', 'app_size', 'status', 'decision', 'decided_by',
       'start_date', 'decided_date', 'target_decision_date',
       'days_to_decision', 'last_changed', 'fetched_at', 'n_comments',
       'n_documents', 'n_statutory_days', 'n_dwellings',
       'housing_relevance_score', 'lat', 'lng', 'ward_name', 'agent_company',
       'case_officer'],
      dtype='object')

In [21]:
list(df.name.unique())

['Barking/21/00003/PRIEXT',
 'Barking/21/00004/CLUP',
 'Barking/21/00006/HSE',
 'Barking/21/00007/HSE',
 'Barking/21/00009/CLUP',
 'Barking/21/00011/CLUP',
 'Barking/21/00012/PRIEXT',
 'Barking/21/00013/CLUP',
 'Barking/21/00014/HSE',
 'Barking/21/00015/HSE',
 'Barking/21/00016/CLUP',
 'Barking/21/00017/HSE',
 'Barking/21/00020/HSE',
 'Barking/21/00021/HSE',
 'Barking/21/00022/CLUP',
 'Barking/21/00024/FULL',
 'Barking/21/00031/CLUP',
 'Barking/21/00035/HSE',
 'Barking/21/00048/HSE',
 'Barking/21/00056/CLUP',
 'Barking/21/00060/CLUP',
 'Barking/21/00061/HSE',
 'Barking/21/00062/HSE',
 'Barking/21/00064/CLUP',
 'Barking/21/00068/CLUP',
 'Barking/21/00073/CLUP',
 'Barking/21/00074/HSE',
 'Barking/21/00075/FULL',
 'Barking/21/00076/HSE',
 'Barking/21/00079/HSE',
 'Barking/21/00081/HSE',
 'Barking/21/00082/CLUP',
 'Barking/21/00085/HSE',
 'Barking/21/00086/CLUP',
 'Barking/21/00087/FULL',
 'Barking/21/00088/CLUP',
 'Barking/21/00095/CLUP',
 'Barking/21/00096/FULL',
 'Barking/21/00097/HSE',
 'Barking/21/00099/HSE',
 'Barking/21/00100/HSE',
 'Barking/21/00102/HSE',
 'Barking/21/00104/HSE',
 'Barking/21/00107/HSE',
 'Barking/21/00109/HSE',
 'Barking/21/00113/CLUP',
 'Barking/21/00116/HSE',
 'Barking/21/00117/HSE',
 'Barking/21/00119/CLUP',
 'Barking/21/00120/CLUP',
 'Barking/21/00121/CLUP',
 'Barking/21/00124/HSE',
 'Barking/21/00125/HSE',
 'Barking/21/00126/HSE',
 'Barking/21/00131/HSE',
 'Barking/21/00132/HSE',
 'Barking/21/00133/FULL',
 'Barking/21/00135/HSE',
 'Barking/21/00138/FULL',
 'Barking/21/00139/HSE',
 'Barking/21/00141/HSE',
 'Barking/21/00142/CLUP',
 'Barking/21/00143/CLUP',
 'Barking/21/00144/HSE',
 'Barking/21/00145/FULL',
 'Barking/21/00147/HSE',
 'Barking/21/00150/HSE',
 'Barking/21/00152/FULL',
 'Barking/21/00154/HSE',
 'Barking/21/00156/CLUP',
 'Barking/21/00158/HSE',
 'Barking/21/00159/FULL',
 'Barking/21/00160/FULL',
 'Barking/21/00165/NONMAT',
 'Barking/21/00166/HSE',
 'Barking/21/00169/CLUP',
 'Barking/21/00170/HSE',
 'Barking/21/00171/HSE',
 'Barking/21/00173/HSE',
 'Barking/21/00174/HSE',
 'Barking/21/00180/CLUP',
 'Barking/21/00181/CLUP',
 'Barking/21/00182/CLUP',
 'Barking/21/00185/HSE',
 'Barking/21/00186/HSE',
 'Barking/21/00188/HSE',
 'Barking/21/00189/HSE',
 'Barking/21/00191/CLUP',
 'Barking/21/00194/CLUP',
 'Barking/21/00197/CLUP',
 'Barking/21/00200/CLUP',
 'Barking/21/00203/HSE',
 'Barking/21/00205/HSE',
 'Barking/21/00206/HSE',
 'Barking/21/00207/HSE',
 'Barking/21/00209/CLUP',
 'Barking/21/00210/HSE',
 'Barking/21/00214/CLUP',
 'Barking/21/00216/HSE',
 'Barking/21/00219/NONMAT',
 'Barking/21/00220/HSE',
 'Barking/21/00223/HSE',
 'Barking/21/00225/CLUP',
 'Barking/21/00227/FULL',
 'Barking/21/00231/HSE',
 'Barking/21/00233/HSE',
 'Barking/21/00234/HSE',
 'Barking/21/00235/CLUP',
 'Barking/21/00237/HSE',
 'Barking/21/00239/FULL',
 'Barking/21/00240/HSE',
 'Barking/21/00241/FULL',
 'Barking/21/00244/CLUP',
 'Barking/21/00246/HSE',
 'Barking/21/00247/CLUP',
 'Barking/21/00249/FULL',
 'Barking/21/00250/VAR',
 'Barking/21/00254/FULL',
 'Barking/21/00255/CLUP',
 'Barking/21/00259/HSE',
 'Barking/21/00261/FULL',
 'Barking/21/00262/CLUP',
 'Barking/21/00266/CLUP',
 'Barking/21/00268/HSE',
 'Barking/21/00272/HSE',
 'Barking/21/00273/HSE',
 'Barking/21/00275/PRIDEM',
 'Barking/21/00276/CLUP',
 'Barking/21/00277/HSE',
 'Barking/21/00278/CLUP',
 'Barking/21/00279/HSE',
 'Barking/21/00281/CLUP',
 'Barking/21/00282/HSE',
 'Barking/21/00283/FULL',
 'Barking/21/00284/FULL',
 'Barking/21/00286/HSE',
 'Barking/21/00287/CLUP',
 'Barking/21/00290/CLUP',
 'Barking/21/00296/FULL',
 'Barking/21/00297/FULL',
 'Barking/21/00299/CLUP',
 'Barking/21/00300/CLUP',
 'Barking/21/00301/HSE',
 'Barking/21/00303/CLUP',
 'Barking/21/00305/FULL',
 'Barking/21/00306/CLUP',
 'Barking/21/00309/CLUP',
 'Barking/21/00312/HSE',
 'Barking/21/00314/HSE',
 'Barking/21/00321/CLUP',
 'Barking/21/00323/CLUP',
 'Barking/21/00327/HSE',
 'Barking/21/00328/HSE',
 'Barking/21/00329/CLUP',
 'Barking/21/00330/HSE',
 'Barking/21/00331/CLUP',
 'Barking/21/00333/HSE',
 'Barking/21/00334/CLUP',
 'Barking/21/00338/HSE',
 'Barking/21/00339/CLUP',
 'Barking/21/00344/HSE',
 'Barking/21/00346/CLUP',
 'Barking/21/00348/HSE',
 'Barking/21/00349/CLUP',
 'Barking/21/00351/FULL',
 'Barking/21/00352/CLUP',
 'Barking/21/00353/HSE',
 'Barking/21/00354/HSE',
 'Barking/21/00355/CLUP',
 'Barking/21/00357/CLUP',
 'Barking/21/00358/FULL',
 'Barking/21/00359/HSE',
 'Barking/21/00361/HSE',
 'Barking/21/00362/CLUP',
 'Barking/21/00363/HSE',
 'Barking/21/00366/HSE',
 'Barking/21/00369/CLUP',
 'Barking/21/00370/CLUP',
 'Barking/21/00371/CLUP',
 'Barking/21/00372/CLUP',
 'Barking/21/00374/HSE',
 'Barking/21/00376/CLUP',
 'Barking/21/00380/FULL',
 'Barking/21/00382/CLUP',
 'Barking/21/00385/HSE',
 'Barking/21/00386/HSE',
 'Barking/21/00388/CLUP',
 'Barking/21/00390/HSE',
 'Barking/21/00391/CLUP',
 'Barking/21/00393/CLUP',
 'Barking/21/00395/PRIRDW',
 'Barking/21/00396/PRIRDW',
 'Barking/21/00397/PRIRDW',
 'Barking/21/00398/HSE',
 'Barking/21/00399/CLUP',
 'Barking/21/00401/CLUP',
 'Barking/21/00403/CLUP',
 'Barking/21/00405/HSE',
 'Barking/21/00407/CLUP',
 'Barking/21/00409/CLUP',
 'Barking/21/00415/CLUP',
 'Barking/21/00416/CLUP',
 'Barking/21/00417/HSE',
 'Barking/21/00419/CLUP',
 'Barking/21/00420/CLUP',
 'Barking/21/00426/HSE',
 'Barking/21/00429/HSE',
 'Barking/21/00431/CLUP',
 'Barking/21/00434/HSE',
 'Barking/21/00437/HSE',
 'Barking/21/00439/HSE',
 'Barking/21/00443/HSE',
 'Barking/21/00445/CLUP',
 'Barking/21/00446/HSE',
 'Barking/21/00447/FULL',
 'Barking/21/00448/HSE',
 'Barking/21/00449/HSE',
 'Barking/21/00450/HSE',
 'Barking/21/00453/HSE',
 'Barking/21/00456/HSE',
 'Barking/21/00457/CLUP',
 'Barking/21/00458/HSE',
 'Barking/21/00464/HSE',
 'Barking/21/00469/CLUP',
 'Barking/21/00471/HSE',
 'Barking/21/00473/FULL',
 'Barking/21/00474/PRICOM',
 'Barking/21/00481/HSE',
 'Barking/21/00484/VAR',
 'Barking/21/00487/FULL',
 'Barking/21/00490/CLUP',
 'Barking/21/00491/CLUP',
 'Barking/21/00492/HSE',
 'Barking/21/00493/HSE',
 'Barking/21/00495/HSE',
 'Barking/21/00497/HSE',
 'Barking/21/00500/HSE',
 'Barking/21/00502/CLUP',
 'Barking/21/00508/CLUP',
 'Barking/21/00509/CLUP',
 'Barking/21/00510/CLUP',
 'Barking/21/00513/FULL',
 'Barking/21/00514/HSE',
 'Barking/21/00516/CLUP',
 'Barking/21/00517/CLUP',
 'Barking/21/00520/CLUP',
 'Barking/21/00521/HSE',
 'Barking/21/00523/CLUP',
 'Barking/21/00524/HSE',
 'Barking/21/00525/CLUP',
 'Barking/21/00527/HSE',
 'Barking/21/00531/HSE',
 'Barking/21/00535/HSE',
 'Barking/21/00536/CLUP',
 'Barking/21/00538/CLUP',
 'Barking/21/00540/HSE',
 'Barking/21/00542/CLUP',
 'Barking/21/00544/HSE',
 'Barking/21/00548/VAR',
 'Barking/21/00549/HSE',
 'Barking/21/00552/CLUP',
 'Barking/21/00553/CLUP',
 'Barking/21/00555/HSE',
 'Barking/21/00557/CLUP',
 'Barking/21/00559/CLUP',
 'Barking/21/00563/HSE',
 'Barking/21/00564/HSE',
 'Barking/21/00566/CLUP',
 'Barking/21/00567/HSE',
 'Barking/21/00569/HSE',
 'Barking/21/00571/HSE',
 'Barking/21/00574/CLUP',
 'Barking/21/00577/HSE',
 'Barking/21/00582/CLUP',
 'Barking/21/00583/PRIOFF',
 'Barking/21/00587/CLUP',
 'Barking/21/00588/HSE',
 'Barking/21/00589/HSE',
 'Barking/21/00590/HSE',
 'Barking/21/00591/HSE',
 'Barking/21/00592/HSE',
 'Barking/21/00594/HSE',
 'Barking/21/00596/CLUP',
 'Barking/21/00597/CLUP',
 'Barking/21/00598/CLUP',
 'Barking/21/00599/CLUP',
 'Barking/21/00602/HSE',
 'Barking/21/00603/HSE',
 'Barking/21/00611/HSE',
 'Barking/21/00616/HSE',
 'Barking/21/00617/HSE',
 'Barking/21/00619/HSE',
 'Barking/21/00621/FULL',
 'Barking/21/00624/CLUP',
 'Barking/21/00628/NONMAT',
 'Barking/21/00629/HSE',
 'Barking/21/00632/CLUP',
 'Barking/21/00648/CLUP',
 'Barking/21/00649/CLUP',
 'Barking/21/00650/CLUP',
 'Barking/21/00653/CLUP',
 'Barking/21/00654/HSE',
 'Barking/21/00657/HSE',
 'Barking/21/00658/FULL',
 'Barking/21/00667/HSE',
 'Barking/21/00670/CLUP',
 'Barking/21/00671/HSE',
 'Barking/21/00674/FULL',
 'Barking/21/00683/HSE',
 'Barking/21/00687/PRIEXT',
 'Barking/21/00690/HSE',
 'Barking/21/00695/CLUP',
 'Barking/21/00696/HSE',
 'Barking/21/00699/HSE',
 'Barking/21/00700/HSE',
 'Barking/21/00701/CLUP',
 'Barking/21/00702/CLUP',
 'Barking/21/00704/CLUP',
 'Barking/21/00707/NONMAT',
 'Barking/21/00710/HSE',
 'Barking/21/00711/HSE',
 'Barking/21/00713/CLUP',
 'Barking/21/00717/HSE',
 'Barking/21/00720/HSE',
 'Barking/21/00722/CLUP',
 'Barking/21/00723/CLUP',
 'Barking/21/00727/HSE',
 'Barking/21/00729/HSE',
 'Barking/21/00730/HSE',
 'Barking/21/00733/FULL',
 'Barking/21/00736/FULL',
 'Barking/21/00738/CLUP',
 'Barking/21/00742/CLUP',
 'Barking/21/00748/CLUP',
 'Barking/21/00751/HSE',
 'Barking/21/00755/HSE',
 'Barking/21/00756/CLUP',
 'Barking/21/00757/HSE',
 'Barking/21/00760/CLUP',
 'Barking/21/00762/HSE',
 'Barking/21/00763/CLUP',
 'Barking/21/00765/CLUP',
 'Barking/21/00768/CLUP',
 'Barking/21/00771/CLUP',
 'Barking/21/00773/FULL',
 'Barking/21/00775/CLUP',
 'Barking/21/00777/HSE',
 'Barking/21/00778/CLUP',
 'Barking/21/00780/CLUP',
 'Barking/21/00782/HSE',
 'Barking/21/00784/CLUP',
 'Barking/21/00785/FULL',
 'Barking/21/00790/FULL',
 'Barking/21/00792/HSE',
 'Barking/21/00793/CLUP',
 'Barking/21/00796/FULL',
 'Barking/21/00805/CLUP',
 'Barking/21/00808/HSE',
 'Barking/21/00809/FULL',
 'Barking/21/00810/HSE',
 'Barking/21/00811/HSE',
 'Barking/21/00812/HSE',
 'Barking/21/00813/HSE',
 'Barking/21/00814/FULL',
 'Barking/21/00816/HSE',
 'Barking/21/00817/HSE',
 'Barking/21/00825/HSE',
 'Barking/21/00827/HSE',
 'Barking/21/00828/HSE',
 'Barking/21/00831/HSE',
 'Barking/21/00836/CLUP',
 'Barking/21/00837/HSE',
 'Barking/21/00839/HSE',
 'Barking/21/00842/HSE',
 'Barking/21/00843/HSE',
 'Barking/21/00845/HSE',
 'Barking/21/00846/HSE',
 'Barking/21/00847/HSE',
 'Barking/21/00849/CLUP',
 'Barking/21/00850/CLUP',
 'Barking/21/00857/CLUP',
 'Barking/21/00858/CLUP',
 'Barking/21/00864/CLUP',
 'Barking/21/00865/HSE',
 'Barking/21/00866/HSE',
 'Barking/21/00867/CLUP',
 'Barking/21/00868/CLUP',
 'Barking/21/00869/CLUP',
 'Barking/21/00880/CLUP',
 'Barking/21/00882/CLUP',
 'Barking/21/00883/FULL',
 'Barking/21/00884/CLUP',
 'Barking/21/00886/CLUP',
 'Barking/21/00887/HSE',
 'Barking/21/00888/CLUP',
 'Barking/21/00889/HSE',
 'Barking/21/00890/HSE',
 'Barking/21/00898/HSE',
 'Barking/21/00901/HSE',
 'Barking/21/00902/HSE',
 'Barking/21/00904/HSE',
 'Barking/21/00905/CLUP',
 'Barking/21/00906/HSE',
 'Barking/21/00907/HSE',
 'Barking/21/00912/FULL',
 'Barking/21/00914/HSE',
 'Barking/21/00915/FULL',
 'Barking/21/00920/HSE',
 'Barking/21/00923/CLUP',
 'Barking/21/00925/HSE',
 'Barking/21/00926/CLUP',
 'Barking/21/00927/HSE',
 'Barking/21/00932/HSE',
 'Barking/21/00936/HSE',
 'Barking/21/00937/CLUP',
 'Barking/21/00938/HSE',
 'Barking/21/00939/HSE',
 'Barking/21/00942/HSE',
 'Barking/21/00948/NONMAT',
 'Barking/21/00950/HSE',
 'Barking/21/00955/HSE',
 'Barking/21/00959/HSE',
 'Barking/21/00962/CLUP',
 'Barking/21/00964/HSE',
 'Barking/21/00969/CLUP',
 'Barking/21/00975/HSE',
 'Barking/21/00976/HSE',
 'Barking/21/00977/FULL',
 'Barking/21/00984/CLUP',
 'Barking/21/00985/CLUP',
 'Barking/21/00986/CLUP',
 'Barking/21/00988/CLUP',
 'Barking/21/00989/CLUP',
 'Barking/21/00991/HSE',
 'Barking/21/00994/HSE',
 'Barking/21/00996/HSE',
 'Barking/21/00997/NONMAT',
 'Barking/21/00999/PRIRET',
 'Barking/21/01008/CLUP',
 'Barking/21/01009/CLUP',
 'Barking/21/01010/CLUP',
 'Barking/21/01014/VAR',
 'Barking/21/01017/HSE',
 'Barking/21/01018/NONMAT',
 'Barking/21/01025/HSE',
 'Barking/21/01026/CLUP',
 'Barking/21/01029/HSE',
 'Barking/21/01030/HSE',
 'Barking/21/01032/HSE',
 'Barking/21/01036/HSE',
 'Barking/21/01037/HSE',
 'Barking/21/01042/FULL',
 'Barking/21/01045/HSE',
 'Barking/21/01049/FULL',
 'Barking/21/01052/HSE',
 'Barking/21/01056/NONMAT',
 'Barking/21/01059/CLUP',
 'Barking/21/01060/HSE',
 'Barking/21/01064/CLUP',
 'Barking/21/01065/NONMAT',
 'Barking/21/01070/NONMAT',
 'Barking/21/01072/CLUP',
 'Barking/21/01078/FULL',
 'Barking/21/01082/CLUP',
 'Barking/21/01083/CLUP',
 'Barking/21/01084/HSE',
 'Barking/21/01085/PRIDEM',
 'Barking/21/01087/HSE',
 'Barking/21/01088/HSE',
 'Barking/21/01090/CLUP',
 'Barking/21/01093/NONMAT',
 'Barking/21/01094/HSE',
 'Barking/21/01097/FULL',
 'Barking/21/01098/HSE',
 'Barking/21/01100/CLUP',
 'Barking/21/01101/FULL',
 'Barking/21/01103/FULL',
 'Barking/21/01106/FULL',
 'Barking/21/01107/NONMAT',
 'Barking/21/01110/HSE',
 'Barking/21/01113/FULL',
 'Barking/21/01116/CLUP',
 'Barking/21/01117/HSE',
 'Barking/21/01118/CLUP',
 'Barking/21/01119/HSE',
 'Barking/21/01120/CLUP',
 'Barking/21/01121/HSE',
 'Barking/21/01123/CLUP',
 'Barking/21/01138/HSE',
 'Barking/21/01139/HSE',
 'Barking/21/01141/NONMAT',
 'Barking/21/01145/CLUP',
 'Barking/21/01150/CLUP',
 'Barking/21/01151/HSE',
 'Barking/21/01152/HSE',
 'Barking/21/01153/HSE',
 'Barking/21/01157/HSE',
 'Barking/21/01165/CLUP',
 'Barking/21/01171/REM',
 'Barking/21/01175/FULL',
 'Barking/21/01176/CLUP',
 'Barking/21/01179/HSE',
 'Barking/21/01180/FULL',
 'Barking/21/01181/HSE',
 'Barking/21/01182/HSE',
 'Barking/21/01184/CLUP',
 'Barking/21/01185/HSE',
 'Barking/21/01187/HSE',
 'Barking/21/01189/FULL',
 'Barking/21/01190/FULL',
 'Barking/21/01194/CLUP',
 'Barking/21/01195/CLUP',
 'Barking/21/01196/HSE',
 'Barking/21/01198/CLUP',
 'Barking/21/01199/CLUP',
 'Barking/21/01202/HSE',
 'Barking/21/01203/HSE',
 'Barking/21/01205/HSE',
 'Barking/21/01207/HSE',
 'Barking/21/01208/HSE',
 'Barking/21/01217/HSE',
 'Barking/21/01218/CLUP',
 'Barking/21/01220/CLUP',
 'Barking/21/01222/CLUP',
 'Barking/21/01225/FULL',
 'Barking/21/01226/PRIRET',
 'Barking/21/01227/CLUP',
 'Barking/21/01229/HSE',
 'Barking/21/01232/FULL',
 'Barking/21/01234/CLUP',
 'Barking/21/01237/CLUP',
 'Barking/21/01240/CLUP',
 'Barking/21/01248/HSE',
 'Barking/21/01254/CLUP',
 'Barking/21/01255/CLUP',
 'Barking/21/01259/CLUP',
 'Barking/21/01260/FULL',
 'Barking/21/01262/HSE',
 'Barking/21/01268/HSE',
 'Barking/21/01269/CLUP',
 'Barking/21/01270/CLUP',
 'Barking/21/01271/FULL',
 'Barking/21/01272/FULL',
 'Barking/21/01273/CLUP',
 'Barking/21/01281/HSE',
 'Barking/21/01282/CLUP',
 'Barking/21/01283/CLUP',
 'Barking/21/01284/NONMAT',
 'Barking/21/01285/NONMAT',
 'Barking/21/01287/OUTALL',
 'Barking/21/01289/PRIDEM',
 'Barking/21/01291/HSE',
 'Barking/21/01292/HSE',
 'Barking/21/01296/HSE',
 'Barking/21/01297/HSE',
 'Barking/21/01298/HSE',
 'Barking/21/01299/FULL',
 'Barking/21/01301/HSE',
 'Barking/21/01303/CLUP',
 'Barking/21/01306/HSE',
 'Barking/21/01308/HSE',
 'Barking/21/01309/CLUP',
 'Barking/21/01310/CLUP',
 'Barking/21/01312/FULL',
 'Barking/21/01314/HSE',
 'Barking/21/01315/HSE',
 'Barking/21/01320/FULL',
 'Barking/21/01321/HSE',
 'Barking/21/01322/HSE',
 'Barking/21/01323/FULL',
 'Barking/21/01324/HSE',
 'Barking/21/01328/CLUP',
 'Barking/21/01329/HSE',
 'Barking/21/01330/HSE',
 'Barking/21/01332/FULL',
 'Barking/21/01333/FULL',
 'Barking/21/01334/CLUP',
 'Barking/21/01336/REM',
 'Barking/21/01337/CLUP',
 'Barking/21/01343/CLUP',
 'Barking/21/01344/CLUP',
 'Barking/21/01347/CLUP',
 'Barking/21/01351/VAR',
 'Barking/21/01354/VAR',
 'Barking/21/01356/CLUP',
 'Barking/21/01360/HSE',
 'Barking/21/01361/HSE',
 'Barking/21/01362/HSE',
 'Barking/21/01364/CLUP',
 'Barking/21/01365/HSE',
 'Barking/21/01366/HSE',
 'Barking/21/01367/HSE',
 'Barking/21/01368/HSE',
 'Barking/21/01374/HSE',
 'Barking/21/01376/HSE',
 'Barking/21/01377/FULL',
 'Barking/21/01378/HSE',
 'Barking/21/01379/HSE',
 'Barking/21/01380/CLUP',
 'Barking/21/01391/CLUE',
 'Barking/21/01392/CLUP',
 'Barking/21/01394/HSE',
 'Barking/21/01395/HSE',
 'Barking/21/01396/HSE',
 'Barking/21/01398/FULL',
 'Barking/21/01402/HSE',
 'Barking/21/01404/CLUP',
 'Barking/21/01406/HSE',
 'Barking/21/01407/FULL',
 'Barking/21/01412/HSE',
 'Barking/21/01414/CLUP',
 'Barking/21/01415/CLUP',
 'Barking/21/01419/HSE',
 'Barking/21/01421/FULL',
 'Barking/21/01423/CLUP',
 'Barking/21/01424/CLUP',
 'Barking/21/01425/CLUP',
 'Barking/21/01435/CLUP',
 'Barking/21/01438/CLUP',
 'Barking/21/01441/CLUP',
 'Barking/21/01443/HSE',
 'Barking/21/01444/CLUP',
 'Barking/21/01445/FULL',
 'Barking/21/01447/CLUP',
 'Barking/21/01451/NONMAT',
 'Barking/21/01453/HSE',
 'Barking/21/01456/HSE',
 'Barking/21/01457/HSE',
 'Barking/21/01465/HSE',
 'Barking/21/01466/CLUP',
 'Barking/21/01472/CLUP',
 'Barking/21/01480/CLUP',
 'Barking/21/01487/NONMAT',
 'Barking/21/01488/CLUP',
 'Barking/21/01491/HSE',
 'Barking/21/01492/FULL',
 'Barking/21/01497/HSE',
 'Barking/21/01498/CLUP',
 'Barking/21/01505/FULL',
 'Barking/21/01505/HSE',
 'Barking/21/01507/HSE',
 'Barking/21/01509/CLUP',
 'Barking/21/01511/FULL',
 'Barking/21/01519/HSE',
 'Barking/21/01520/HSE',
 'Barking/21/01537/CLUP',
 'Barking/21/01538/HSE',
 'Barking/21/01539/CLUP',
 'Barking/21/01540/CLUP',
 'Barking/21/01542/CLUP',
 'Barking/21/01543/HSE',
 'Barking/21/01544/HSE',
 'Barking/21/01545/CLUP',
 'Barking/21/01546/HSE',
 'Barking/21/01558/FULL',
 'Barking/21/01563/HSE',
 'Barking/21/01564/HSE',
 'Barking/21/01567/CLUE',
 'Barking/21/01568/HSE',
 'Barking/21/01570/FULL',
 'Barking/21/01573/PRIMA',
 'Barking/21/01575/CLUP',
 'Barking/21/01576/CLUP',
 'Barking/21/01577/FULL',
 'Barking/21/01578/HSE',
 'Barking/21/01581/NONMAT',
 'Barking/21/01585/FULL',
 'Barking/21/01586/HSE',
 'Barking/21/01588/FULL',
 'Barking/21/01591/FULL',
 'Barking/21/01592/CLUP',
 'Barking/21/01593/CLUP',
 'Barking/21/01594/HSE',
 'Barking/21/01595/CLUP',
 'Barking/21/01596/HSE',
 'Barking/21/01598/HSE',
 'Barking/21/01599/HSE',
 'Barking/21/01600/CLUP',
 'Barking/21/01603/HSE',
 'Barking/21/01604/HSE',
 'Barking/21/01605/HSE',
 'Barking/21/01607/HSE',
 'Barking/21/01608/HSE',
 'Barking/21/01611/HSE',
 'Barking/21/01612/CLUP',
 'Barking/21/01615/FULL',
 'Barking/21/01616/LBC',
 'Barking/21/01617/HSE',
 'Barking/21/01618/HSE',
 'Barking/21/01620/HSE',
 'Barking/21/01621/HSE',
 'Barking/21/01622/HSE',
 'Barking/21/01623/FULL',
 'Barking/21/01624/NONMAT',
 'Barking/21/01626/HSE',
 'Barking/21/01636/CLUP',
 'Barking/21/01637/CLUP',
 'Barking/21/01638/CLUP',
 'Barking/21/01643/HSE',
 'Barking/21/01646/CLUP',
 'Barking/21/01647/CLUP',
 'Barking/21/01649/FULL',
 'Barking/21/01651/HSE',
 'Barking/21/01652/HSE',
 'Barking/21/01654/PRIDEM',
 'Barking/21/01656/CLUP',
 'Barking/21/01658/CLUP',
 'Barking/21/01662/HSE',
 'Barking/21/01665/FULL',
 'Barking/21/01669/CLUP',
 'Barking/21/01670/CLUP',
 'Barking/21/01674/FULL',
 'Barking/21/01676/HSE',
 'Barking/21/01678/FULL',
 'Barking/21/01680/HSE',
 'Barking/21/01683/HSE',
 'Barking/21/01687/CLUP',
 'Barking/21/01688/HSE',
 'Barking/21/01689/CLUP',
 'Barking/21/01690/FULL',
 'Barking/21/01691/FULL',
 'Barking/21/01694/CLUP',
 'Barking/21/01695/CLUP',
 'Barking/21/01707/CLUP',
 'Barking/21/01711/FULL',
 'Barking/21/01715/HSE',
 'Barking/21/01716/HSE',
 'Barking/21/01718/HSE',
 'Barking/21/01727/HSE',
 'Barking/21/01735/CLUP',
 'Barking/21/01736/CLUP',
 'Barking/21/01738/CLUP',
 'Barking/21/01746/CLUP',
 'Barking/21/01748/CLUP',
 'Barking/21/01752/FULL',
 'Barking/21/01753/HSE',
 'Barking/21/01757/FULL',
 'Barking/21/01758/HSE',
 'Barking/21/01764/NONMAT',
 'Barking/21/01768/CLUP',
 'Barking/21/01769/HSE',
 'Barking/21/01771/CLUP',
 'Barking/21/01773/HSE',
 'Barking/21/01776/FULL',
 'Barking/21/01780/CLUP',
 'Barking/21/01782/FULL',
 'Barking/21/01785/CLUE',
 'Barking/21/01788/FULL',
 'Barking/21/01789/CLUP',
 'Barking/21/01791/FULL',
 'Barking/21/01792/CLUP',
 'Barking/21/01794/CLUP',
 'Barking/21/01797/FULL',
 'Barking/21/01801/CLUP',
 'Barking/21/01803/OUTALL',
 'Barking/21/01805/PRIDEM',
 'Barking/21/01807/HSE',
 'Barking/21/01808/OUTALL',
 'Barking/21/01809/CLUP',
 'Barking/21/01811/FULL',
 'Barking/21/01813/NONMAT',
 'Barking/21/01815/HSE',
 'Barking/21/01819/CLUP',
 'Barking/21/01820/FULL',
 'Barking/21/01821/FULL',
 'Barking/21/01822/HSE',
 'Barking/21/01825/HSE',
 'Barking/21/01827/CLUP',
 'Barking/21/01830/CLUE',
 'Barking/21/01837/FULL',
 'Barking/21/01841/HSE',
 'Barking/21/01844/CLUP',
 'Barking/21/01845/HSE',
 'Barking/21/01854/CLUP',
 'Barking/21/01865/HSE',
 'Barking/21/01868/HSE',
 'Barking/21/01870/HSE',
 'Barking/21/01873/NONMAT',
 'Barking/21/01877/HSE',

In [22]:
df_dropped = df.drop(columns=['name', 'url','n_comments', 'n_documents', 'n_statutory_days', 'case_officer'])

In [23]:
df_dropped.columns

Index(['area_name', 'reference', 'uid', 'description', 'app_type', 'app_size',
       'status', 'decision', 'decided_by', 'start_date', 'decided_date',
       'target_decision_date', 'days_to_decision', 'last_changed',
       'fetched_at', 'n_dwellings', 'housing_relevance_score', 'lat', 'lng',
       'ward_name', 'agent_company'],
      dtype='object')

In [24]:
df_dropped['uid'].head(10)

146    21/00003/PRIEXT
147      21/00004/CLUP
148       21/00006/HSE
149       21/00007/HSE
150      21/00009/CLUP
151      21/00011/CLUP
152    21/00012/PRIEXT
153      21/00013/CLUP
154       21/00014/HSE
155       21/00015/HSE
Name: uid, dtype: object

In [25]:
'PRIEXT', 'CLUP','LBC', 'FUL', 'OUT', 'RES / REM', 'PRIOR / PA / PNDEM'

('PRIEXT', 'CLUP', 'LBC', 'FUL', 'OUT', 'RES / REM', 'PRIOR / PA / PNDEM')

In [26]:
df[['decision', 'decided_by', 'start_date', 'decided_date',
       'target_decision_date', 'days_to_decision', 'last_changed',
       'fetched_at']]

,decision,decided_by,start_date,decided_date,target_decision_date,days_to_decision,last_changed,fetched_at
146,Prior Approval Not Required,None,2021-01-05,2021-02-12,NaT,38.0,2026-04-04 07:44:42.135733+00:00,2026-08-10 03:59:32.318132+00:00
147,Lawful (Certificate),None,2021-01-07,2021-02-01,NaT,25.0,2026-04-25 07:43:31.721126+00:00,2026-08-10 03:59:32.318132+00:00
148,Approved,None,2021-01-04,2021-02-15,NaT,42.0,2026-05-02 07:44:32.624829+00:00,2026-08-10 03:59:32.318132+00:00
149,Approved,None,2021-01-04,2021-02-15,NaT,42.0,2026-04-04 07:44:42.127157+00:00,2026-08-10 03:59:32.318132+00:00
150,Lawful (Certificate),None,2021-01-04,2021-01-29,NaT,25.0,2026-05-30 07:49:21.090674+00:00,2026-08-10 03:59:32.318132+00:00
...,...,...,...,...,...,...,...,...
243921,No Comment,Delegated Decision,2025-12-12,2026-03-04,2026-01-02,82.0,2026-08-01 14:37:33.449539+00:00,2026-08-05 21:30:42.191535+00:00
243922,No Comment,Delegated Decision,2025-12-11,2026-02-12,2026-01-01,63.0,2026-08-01 14:37:33.732500+00:00,2026-08-05 21:30:42.191535+00:00
243923,No objections,Delegated Decision,2025-12-22,2026-03-03,2026-01-12,71.0,2026-07-18 16:55:22.930361+00:00,2026-08-05 21:28:41.110580+00:00
243924,No objections,Delegated Decision,2025-12-22,2026-03-03,2026-01-12,71.0,2026-07-18 16:55:22.926110+00:00,2026-08-05 21:28:41.110580+00:00
243925,Application Permitted,Delegated Decision,2025-12-08,2026-06-05,2026-01-05,179.0,2026-07-27 09:52:44.954462+00:00,2026-08-05 21:32:43.267722+00:00

In [ ]:
bins = int(df['days_to_decision'].max() - df['days_to_decision'].min())
print(df['days_to_decision'].max())
print(df['days_to_decision'].min())
plt.hist(df_dropped['days_to_decision'], bins=bins, edgecolor='black')
plt.axvline(df_dropped['days_to_decision'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')
plt.legend()
plt.title(f'Distribution of Days to Decision')
plt.xlabel('Days to Decision')
plt.ylabel('Frequency')
plt.xlim(0, df['days_to_decision'].max())
plt.show()

In [28]:
df.columns

Index(['name', 'area_name', 'reference', 'uid', 'url', 'description',
       'app_type', 'app_size', 'status', 'decision', 'decided_by',
       'start_date', 'decided_date', 'target_decision_date',
       'days_to_decision', 'last_changed', 'fetched_at', 'n_comments',
       'n_documents', 'n_statutory_days', 'n_dwellings',
       'housing_relevance_score', 'lat', 'lng', 'ward_name', 'agent_company',
       'case_officer'],
      dtype='object')

In [ ]:
df[df['days_to_decision'] >  13*7][['description',
       'app_type', 'app_size', 'status', 'decision', 'decided_by', 'start_date', 'decided_date',
       'target_decision_date', 'days_to_decision']]

In [30]:
print(f'{100*43905/len(df):.3f}%')

18.010%

In [ ]:
for app_type in df['app_type'].unique():
    temp_df = df[(df['app_type'] == app_type) & (df['days_to_decision'] > 0) & (df['days_to_decision'] < 365)]
    bins = int(temp_df['days_to_decision'].max() - temp_df['days_to_decision'].min())
    n, _ , _ = plt.hist(temp_df['days_to_decision'], bins=bins, edgecolor='black')
    plt.axvline(temp_df['days_to_decision'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')
    plt.axvline(56, color='blue', linestyle='dashed', linewidth=1, label='8-week target')
    plt.axvline(13*7, color='green', linestyle='dashed', linewidth=1, label='13-week target')
    if app_type == 'Amendment':
        plt.axvline(4*7, color='red', linestyle='dashed', linewidth=1, label='4-week')
    plt.legend()
    plt.title(f'Distribution of Days to Decision for {app_type}')
    plt.xlabel('Days to Decision')
    plt.ylabel('Frequency')
    plt.ylim(0,n.max() + 100)
    plt.show()

In [32]:
len(df[df['days_to_decision'] <= 56])

114800

In [33]:
df.app_size.unique()

array(['Small', 'Large', 'Medium', ''], dtype=object)

In [45]:
100*len(df[(df['n_dwellings'] > 10) & (df['app_type'] == 'Full') & (df['days_to_decision'] > 8*7)])/len(df[(df['n_dwellings'] > 10) & (df['app_type'] == 'Full')])

58.52713178294574

In [ ]:
for app_type in df['app_type'].unique():
    temp_df = df[(df['app_type'] == app_type) & (df['days_to_decision'] > 0) & (df['days_to_decision'] < 365)
                 & (df['n_dwellings'] > 10)]
    try:
        bins = int(temp_df['days_to_decision'].max() - temp_df['days_to_decision'].min())
        n, _ , _ = plt.hist(temp_df['days_to_decision'], bins=bins, edgecolor='black')
        plt.axvline(temp_df['days_to_decision'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')
        plt.axvline(56, color='blue', linestyle='dashed', linewidth=1, label='8-week target')
        plt.axvline(13*7, color='green', linestyle='dashed', linewidth=1, label='13-week target')
        plt.legend()
        plt.title(f'Distribution of Days to Decision for {app_type}')
        plt.xlabel('Days to Decision')
        plt.ylabel('Frequency')
        plt.ylim(0,n.max() + 10)
        plt.show()
    except ValueError:
        continue

In [57]:
df_dropped.columns

Index(['area_name', 'reference', 'uid', 'description', 'app_type', 'app_size',
       'status', 'decision', 'decided_by', 'start_date', 'decided_date',
       'target_decision_date', 'days_to_decision', 'last_changed',
       'fetched_at', 'n_dwellings', 'housing_relevance_score', 'lat', 'lng',
       'ward_name', 'agent_company'],
      dtype='object')

In [ ]:
plt.hist(df['n_statutory_days'], bins=bins, edgecolor='black', log=True)
plt.axvline(df['n_statutory_days'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')
plt.legend()
plt.title(f'Distribution of Statutory Days')
plt.xlabel('Statutory Days')
plt.ylabel('Frequency')
plt.xlim(0, df['n_statutory_days'].max())
plt.show()

In [68]:
statutory_1000_df = df[df['n_statutory_days'] > 1000]
statutory_1000_df.columns, statutory_1000_df.shape

(Index(['name', 'area_name', 'reference', 'uid', 'url', 'description',
        'app_type', 'app_size', 'status', 'decision', 'decided_by',
        'start_date', 'decided_date', 'target_decision_date',
        'days_to_decision', 'last_changed', 'fetched_at', 'n_comments',
        'n_documents', 'n_statutory_days', 'n_dwellings',
        'housing_relevance_score', 'lat', 'lng', 'ward_name', 'agent_company',
        'case_officer'],
       dtype='object'),
 (4312, 27))

In [ ]:
for app_type in statutory_1000_df['app_type'].unique():
    temp_statutory_1000_df = statutory_1000_df[(statutory_1000_df['n_dwellings'] > 0)]
    try:
        bins = int(temp_statutory_1000_df['n_dwellings'].max() - temp_statutory_1000_df['n_dwellings'].min())
        n, _ , _ = plt.hist(temp_statutory_1000_df['n_dwellings'], bins=bins, edgecolor='black')
        plt.axvline(temp_statutory_1000_df['n_dwellings'].mean(), color='red', linestyle='dashed', linewidth=1, label='Mean')
        plt.axvline(56, color='blue', linestyle='dashed', linewidth=1, label='8-week target')
        plt.axvline(13*7, color='green', linestyle='dashed', linewidth=1, label='13-week target')
        plt.legend()
        plt.title(f'Distribution of Dwellings for {app_type}')
        plt.xlabel('Dwellings')
        plt.ylabel('Frequency')
        plt.ylim(0,n.max() + 10)
        plt.show()
    except ValueError:
        continue